### ISSUE TITLE
Kinda new, so might just be doing it wrong :/

### ISSUE THREAD

**Issue by veryLuckyDucky** [gigabite-pro/byeClicker#2]
Like the title says I'm kinda new to this stuff, but I've run into some problems when trying to download it to Firefox. It seems your extension uses background.Service_worker which Firefox does not like/ support. :( Works like a charm on edge tho, tysm, it's saving my participation grade rn.

**Comment by gigabite-pro** [comment]
Thank you so much. I agree, you must be facing issues on Firefox because it uses different engine in it's browser. However, Chrome, Edge, and Brave use the Chromium engine so it works fine on all of them. It was intended to work on these browsers and never Firefox. Hope that helps :)
